### ISSUE TITLE
Latest version of gauge not installed?

### ISSUE THREAD

**Issue by galacticgumshoe** [gocd-contrib/gauge-cookbook#1]
I was just trying this cookbook to install gauge in my test kitchen, and can see it only installs 0.4.0. Considering gauge is currently at 0.6.1, is it possible to pass in the desired gauge version to be installed? At present, all I can see is that I can pass the version of this cookbook, but that still installs the older version of gauge.

**Comment by galacticgumshoe** [comment]
After reviewing the attribute default.rb file, I can see that the version can be set in my local test kitchen. So in my situation gauge is currently at 0.6.1, but my test suite code is certified on 0.6.0. So I set my attribute in my .kitchen.yml for gauge at 0.6.0 and try to converge my kitchen. It looks like the installation is grabbing the correct version of the zip file from github, but then chokes because the checksum doesn't match. I notice that checksum is another attribute I can set, and the default is still the checksum for the 0.4.0 gauge version. Now I'm stuck because none of the checksums for past versions of the gauge releases are available, only the latest release publishes its checksums. So it would be nice to turn off the behavior of verifying checksum in the scenario where I pass in a version that isn't current and don't also pass in a new checksum to override the default.

```
       ================================================================================
       Error executing action `create` on resource 'remote_file[/tmp/kitchen/cache/gauge-0.6.0-linux.x86_64.zip]'
       ================================================================================

       Chef::Exceptions::ChecksumMismatch
       ----------------------------------
       Checksum on resource (4e2403) does not match checksum on content (507f23)

       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/gauge/recipes/install_linux.rb

         3: remote_file zipfile do
         4:   source node['gauge']['url']
         5:   checksum node['gauge']['checksum']
         6:   not_if { ::File.exist?("/opt/local/gauge/.version-#{node['gauge']['version']}") }
         7: end
         8:

       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/gauge/recipes/install_linux.rb:3:in `from_file'

       remote_file("/tmp/kitchen/cache/gauge-0.6.0-linux.x86_64.zip") do
         provider Chef::Provider::RemoteFile
         action [:create]
         retries 0
         retry_delay 2
         default_guard_interpreter :default
         source ["https://github.com/getgauge/gauge/releases/download/v0.6.0/gauge-0.6.0-linux.x86_64.zip"]
         use_etag true
         use_last_modified true
         declared_type :remote_file
         cookbook_name "gauge"
         recipe_name "install_linux"
         checksum "4e2403472779b8a428bfcc101574b840b1e5221c"
         atomic_update true
         path "/tmp/kitchen/cache/gauge-0.6.0-linux.x86_64.zip"
         not_if { #code block }
       end

       Platform:
       ---------
       x86_64-linux
```

**Comment by galacticgumshoe** [comment]
ok, so my last post: I figured out how to calculate the checksum of the zip file, and passed that in as an attribute, and the gauge engine installed at 0.6.0 in my vagrant test kitchen! so my recommendation with this issue is to update the README and explain how to pass in both a version attribute as well as a checksum attribute (plus how to calculate a checksum would be nice) to resolve this issue.

**Comment by sriv** [comment]
@galacticgumshoe - since you have done most of the research, could you please send a PR for the README?

**Comment by ketan** [comment]
Fixed via https://github.com/getgauge-contrib/gauge-cookbook/commit/3b838ebb0cf7ec6b7239f0acea9de0e0251c0563
